version: '3.8'
services:
  postgres:
    container_name: notes-app-postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: notes-app-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  liquibase:
    container_name: notes-app-liquibase
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://notes-app-postgres:5432/notes-app" --changeLogFile=./changelog/changelog.sql --username=admin --password=root update

volumes:
  postgres-data:
